//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace UMB.Reminder.API
{
	/// <summary>
	/// Database       : reminder
	/// Data Source    : 127.0.0.1
	/// Server Version : 5.5.5-10.1.26-MariaDB
	/// </summary>
	public partial class Reminder : LinqToDB.Data.DataConnection
	{
		public ITable<Admin>        Admins        { get { return this.GetTable<Admin>(); } }
		public ITable<Kelasprogram> Kelasprograms { get { return this.GetTable<Kelasprogram>(); } }
		public ITable<Mahasiswa>    Mahasiswas    { get { return this.GetTable<Mahasiswa>(); } }

		public Reminder()
		{
			InitDataContext();
		}

		public Reminder(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("admin")]
	public partial class Admin
	{
		[PrimaryKey, Identity   ] public int    IDAdmin   { get; set; } // int(20)
		[Column,     NotNull    ] public string NIK       { get; set; } // varchar(20)
		[Column,     NotNull    ] public string Password  { get; set; } // varchar(50)
		[Column,     NotNull    ] public string NamaAdmin { get; set; } // varchar(50)
		[Column,        Nullable] public string Kampus    { get; set; } // varchar(50)
	}

	[Table("kelasprogram")]
	public partial class Kelasprogram
	{
		[PrimaryKey, Identity] public int       IDKelasProgram       { get; set; } // int(20)
		[Column,     Nullable] public string    KodeKelasProgram     { get; set; } // varchar(20)
		[Column,     Nullable] public string    TahunAjaran          { get; set; } // varchar(50)
		[Column,     Nullable] public string    Semester             { get; set; } // varchar(50)
		[Column,     Nullable] public string    KelasProgramReg      { get; set; } // varchar(50)
		[Column,     Nullable] public DateTime? KRSStart             { get; set; } // date
		[Column,     Nullable] public DateTime? KRSEnd               { get; set; } // date
		[Column,     Nullable] public DateTime? PembukaanPerkuliahan { get; set; } // date
		[Column,     Nullable] public DateTime? CutiEnd              { get; set; } // date
		[Column,     Nullable] public DateTime? BatalKrsStart        { get; set; } // date
		[Column,     Nullable] public DateTime? BatalKrsEnd          { get; set; } // date
		[Column,     Nullable] public DateTime? Perkuliahan1Start    { get; set; } // date
		[Column,     Nullable] public DateTime? Perkuliahan1End      { get; set; } // date
		[Column,     Nullable] public DateTime? UTSStart             { get; set; } // date
		[Column,     Nullable] public DateTime? UTSEnd               { get; set; } // date
		[Column,     Nullable] public DateTime? Perkuliahan2Start    { get; set; } // date
		[Column,     Nullable] public DateTime? Perkuliahan2End      { get; set; } // date
		[Column,     Nullable] public DateTime? UASStart             { get; set; } // date
		[Column,     Nullable] public DateTime? UASEnd               { get; set; } // date
		[Column,     Nullable] public DateTime? HasilStudi           { get; set; } // date
		[Column,     Nullable] public string    Status               { get; set; } // varchar(50)

		#region Associations

		/// <summary>
		/// Mahasiswa_KelasProgram_BackReference
		/// </summary>
		[Association(ThisKey="IDKelasProgram", OtherKey="IDKelasProgram", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Mahasiswa> MahasiswaKelasPrograms { get; set; }

		#endregion
	}

	[Table("mahasiswa")]
	public partial class Mahasiswa
	{
		[PrimaryKey, Identity   ] public int       IDMahasiswa    { get; set; } // int(20)
		[Column,     NotNull    ] public string    NIM            { get; set; } // varchar(20)
		[Column,     NotNull    ] public string    Password       { get; set; } // varchar(50)
		[Column,     NotNull    ] public string    NamaMahasiswa  { get; set; } // varchar(50)
		[Column,     NotNull    ] public int       IDKelasProgram { get; set; } // int(20)
		[Column,        Nullable] public string    Fakultas       { get; set; } // varchar(50)
		[Column,        Nullable] public string    Jurusan        { get; set; } // varchar(50)
		[Column,        Nullable] public string    Kampus         { get; set; } // varchar(50)
		[Column,        Nullable] public DateTime? AddDate        { get; set; } // date
		[Column,        Nullable] public string    AddBy          { get; set; } // varchar(50)
		[Column,        Nullable] public DateTime? EditDate       { get; set; } // date
		[Column,        Nullable] public string    EditBy         { get; set; } // varchar(50)

		#region Associations

		/// <summary>
		/// Mahasiswa_KelasProgram
		/// </summary>
		[Association(ThisKey="IDKelasProgram", OtherKey="IDKelasProgram", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="Mahasiswa_KelasProgram", BackReferenceName="MahasiswaKelasPrograms")]
		public Kelasprogram MahasiswaKelasProgram { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Admin Find(this ITable<Admin> table, int IDAdmin)
		{
			return table.FirstOrDefault(t =>
				t.IDAdmin == IDAdmin);
		}

		public static Kelasprogram Find(this ITable<Kelasprogram> table, int IDKelasProgram)
		{
			return table.FirstOrDefault(t =>
				t.IDKelasProgram == IDKelasProgram);
		}

		public static Mahasiswa Find(this ITable<Mahasiswa> table, int IDMahasiswa)
		{
			return table.FirstOrDefault(t =>
				t.IDMahasiswa == IDMahasiswa);
		}
	}
}
